name = "api-aggregator"
main = "index.js"
compatibility_date = "2024-03-26"

# Binding for the Durable Object that acts as a queue manager
[durable_objects]
bindings = [
  { name = "HEALTH_CHECKER", class_name = "HealthCheckerDO" }
]

# Migration for the new Durable Object class
[[migrations]]
tag = "v1"
new_sqlite_classes = ["HealthCheckerDO"]

# KV namespace for the final, cached report
[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "your-proxy-cache-id-here"

# KV namespace for permanent GeoIP data
[[kv_namespaces]]
binding = "GEOIP_CACHE"
id = "your-geoip-kv-id-here"

# Cron trigger to activate the worker pool every minute
[triggers]
crons = ["* * * * *"]

[vars]
PROXY_LIST_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
HEALTH_CHECK_TIMEOUT = "5000"
